type=command
command=/usr/lib/jvm/java-7-openjdk-amd64/bin/java -jar ${GATK_DIR}/mutect-1.1.7.jar \
--analysis_type MuTect \
--input_file:tumor ${dir.output}/${gs.output}_GATK.bam \
--reference_sequence ${REF_GENOME} \
--dbsnp ${DBSNP} \
--cosmic ${COSMIC} \
--out ${dir.output}/${gs.output}.call_stats.g.txt \
--coverage_file ${dir.output}/${gs.output}.coverage.wig.g.txt \
-vcf ${dir.output}/${gs.output}.g.vcf
dependencies=TN_6_PrintReads.cmd
