type=command
command=java -jar ${VarScan_DIR}/VarScan.v2.3.9.jar somatic  BTN-034_Sample_GATK.T.bam.mpileup /mnt/BTN-mileup/BTN-034_Sample_GATK.T.Varscan --mpileup  1
--min-coverage 8 \
 --min-coverage-normal 8 \
 --min-coverage-tumor 6 \
--min-var-freq 0.10 \
--min-freq-for-hom 0.75 \
--normal-purity 1.0 \
--tumor-purity 1.00 \
--p-value 0.99 \
--somatic-p-value 0.05 \
--strand-filter 0 \
--output-vcf
TMP_DIR=${tmp.dir}/${gs.output}
dependencies=TN_8_Mpileup.cmd
