type=command
command=java -Xmx32g -jar ${GATK_DIR}/GenomeAnalysisTK.jar \
-T HaplotypeCaller \
-R ${REF_GENOME} \
--input_file ${dir.output}/${gs.output}_GATK.bam \
--emitRefConfidence GVCF \
-A DepthPerSampleHC \
-A ClippingRankSumTest \
-A MappingQualityRankSumTest \
-A ReadPosRankSumTest \
-A FisherStrand \
-A GCContent \
-A AlleleBalanceBySample \
-A AlleleBalance \
-A QualByDepth \
-pairHMM VECTOR_LOGLESS_CACHING \
-nct ${gatk.NCT} \
-o ${dir.output}/${gs.output}.g.vcf 
dependencies=6_PrintReads.cmd
